---
- name: L2 Interface Config
  hosts: test_switches
  gather_facts: no
  vars:
    interfacetype: GigabitEthernet0
    access_vlan_set: 20

  tasks:
    - name: Set "{{ interfacetype }}/8" to default
      ios_l2_interface:
        name: "{{ interfacetype }}/8"
        state: unconfigured

    - name: Ensure "{{ interfacetype }}/8" is configured for access vlan "{{ access_vlan_set }}"
      ios_l2_interface:
        name: "{{ interfacetype }}/8"
        mode: access
        access_vlan: "{{ access_vlan_set }}"