---
- name: L2 Interface Config
  hosts: test_switches
  gather_facts: no

  tasks:
    - name: Set GigabitEthernet0/8 to default
      ios_l2_interface:
        name: GigabitEthernet0/8
        state: unconfigured

    - name: Ensure GigabitEthernet0/8 is configured for access vlan 30
      ios_l2_interface:
        name: GigabitEthernet0/8
        mode: access
        access_vlan: "30"